name: Deploy Project with Nginx

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy project with Nginx
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}  # Set environment dynamically

      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            # Using GitHub Token for authentication with private repositories
            git config --global url."https://${{ secrets.GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"

            # Check if the repo is already cloned. If not, clone it.
            if [ ! -d "${{ secrets.PROD_DIR }}" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "Cloning production repository..."
              git clone https://github.com/${{ github.repository }} ${{ secrets.PROD_DIR }}
              cd ${{ secrets.PROD_DIR }}
              git checkout main
            elif [ ! -d "${{ secrets.DEV_DIR }}" ] && [ "${{ github.ref }}" == "refs/heads/develop" ]; then
              echo "Cloning development repository..."
              git clone https://github.com/${{ github.repository }} ${{ secrets.DEV_DIR }}
              cd ${{ secrets.DEV_DIR }}
              git checkout develop
            fi

            # If the repo is already cloned, pull the latest changes.
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "Deploying to production..."
              cd ${{ secrets.PROD_DIR }}
              git pull origin main  # Pull from main for production
              npm ci
              npm run frontend
              pm2 restart chatg --update-env
            elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
              echo "Deploying to development..."
              cd ${{ secrets.DEV_DIR }}
              git pull origin develop  # Pull from develop for development
              npm ci
              npm run frontend
              pm2 restart chatg --update-env
            fi

      - name: Update deployment Status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ vars.MY_APP }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
